spring:
 datasource:
  url: jdbc:mysql://localhost:3306/minorproject1_jbdl34?createDatabaseIfNotExist=true
  username: root
  password: root
 jpa:
  hibernate.ddl-auto: create
  show-sql: true
  
server:
 port: 9090
 
custom_property:
 secret_key: 13dgfn4j32j3
 
book:
  return:
    due_date: 14
    
users:
 authority:
  student: std
  admin: adm