spring:
 datasource:
  url: jdbc:mysql://localhost:3306/minorProject_jbdl56?createDatabaseIfNotExist=true
  username: root
  password: root
 jpa:
  hibernate.ddl-auto: update
  show-sql: true 
  
server:
 port: 8085
 
custom_property:
 secret_key: 8ff8fg8erhrhr
 
book:
 maxAllowedDays: 14

users:
 authority:
  student: std
  admin: adm
 