spring:
 datasource:
  url: jdbc:mysql://localhost:3306/minorProject_jbdl34?createDatabaseIfNotExist=true
  username: root
  password: root1234
 jpa:
  hibernate.ddl-auto: create
  show-sql: true 
  
server:
 port: 9090
 
custom_property:
 secret_key: 8ff8fg8erhrhr
 
book:
 maxAllowedDays: 14
 