spring:
  datasource:
    url: jdbc:mysql://localhost:3306/minorproject_jbdl56?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    show-sql: true

server:
  port: 9090